fileVersion: 1
id: "6"
mappingDefinitions:
  SRC:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: BEN_EDW
    schema: QA_STABLE_ENV
name: QA Stable Environment
type: Environment
